name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: etherscan
  - name: hardhat
  - name: infura
  - name: alchemy
  - name: foundry

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: v3.0.0
    contracts_folder: src
    exclude:
      -  src/test/**/*
  - name: periphery
    github: yearn/tokenized-strategy-periphery
    ref: master
    contracts_folder: src
  - name: periphery
    github: yearn/tokenized-strategy-periphery
    ref: master
    contracts_folder: src
  - name: v3-core
    github: 16slim/v3-core
    ref: 1.0.2-solc-0.8-simulate

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.2"
    - "@tokenized-strategy=tokenized-strategy/v3.0.0"
    - "@periphery=periphery/master"
    - "@uniswap/contracts=v3-core/1.0.2-solc-0.8-simulate"
    - "@uniswap=v3-core/1.0.2-solc-0.8-simulate"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: infura
